# Generated by Django 5.2.12 on 2026-04-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='s_completed',
            new_name='is_completed',
        ),
    ]
